import { render, screen } from '@testing-library/react';

import Home from '@/pages/index';
import HeadWrapper from '@/tests/mocks/next/HeadWrapper.mock';

describe('Home component', () => {
  it('renders the head', () => {
    render(<Home />, { wrapper: HeadWrapper });
    expect(document.title).toBe('Create Next App');
    expect(document.head.querySelector('[name="description"]')).toHaveProperty(
      'content',
      'Generated by create next app',
    );
  });

  it('renders the description', () => {
    render(<Home />);
    const descriptionElement = screen.getByText(/Get started by editing/i);
    expect(descriptionElement).toBeInTheDocument();
  });

  // Add more test cases for other functionality
});
